# Generated by Django 5.1.4 on 2025-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
