# Generated by Django 5.1.4 on 2025-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_location_alter_warehouse_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
